module.exports = {
  subreddits: [
    {
      name: 'Am I The Asshole',
      url: 'https://old.reddit.com/r/AmItheAsshole/top/',
      count: 5,
    },
    {
      name: 'AITAH',
      url: 'https://old.reddit.com/r/AITAH/top/',
      count: 5,
    },
    {
      name: 'Relationship Advice',
      url: 'https://old.reddit.com/r/relationship_advice/top/',
      count: 5,
    },
    {
      name: 'Relationships',
      url: 'https://old.reddit.com/r/relationships/top/',
      count: 5,
    },
    {
      name: 'Confession',
      url: 'https://old.reddit.com/r/confession/top/',
      count: 5,
    },
    {
      name: 'Today I Fucked Up',
      url: 'https://old.reddit.com/r/tifu/top/',
      count: 5,
    },
    {
      name: 'Legal Advice',
      url: 'https://old.reddit.com/r/legaladvice/top/',
      count: 5,
    },
    {
      name: 'Entitled Parents',
      url: 'https://old.reddit.com/r/entitledparents/top/',
      count: 5,
    },
    {
      name: 'Off My Chest',
      url: 'https://old.reddit.com/r/offmychest/top/',
      count: 5,
    },
    {
      name: 'True Off My Chest',
      url: 'https://old.reddit.com/r/TrueOffMyChest/top/',
      count: 5,
    },
    {
      name: 'Petty Revenge',
      url: 'https://old.reddit.com/r/pettyrevenge/top/',
      count: 5,
    },
    {
      name: 'Malicious Complience',
      url: 'https://old.reddit.com/r/MaliciousCompliance/top/',
      count: 5,
    },
    {
      name: 'Tales From Tech Support',
      url: 'https://old.reddit.com/r/talesfromtechsupport/top/',
      count: 5,
    },
  ],
  voices: [
    "en_male_jomboy",
    "en_us_002",
    "es_mx_002",
    "en_male_funny",
    "en_us_ghostface",
    "en_female_samc",
    "en_male_cody",
    "en_female_makeup",
    "en_female_richgirl",
    "en_male_grinch",
    "en_us_006",
    "en_male_narration",
    "en_male_deadpool",
    "en_uk_001",
    "en_au_001",
    "en_male_jarvis",
    "en_male_ashmagic",
    "en_male_olantekkers",
    "en_male_ukneighbor",
    "en_male_ukbutler",
    "en_female_shenna",
    "en_female_pansino",
    "en_male_trevor",
    "en_female_f08_twinkle",
    "en_male_m03_classical",
    "en_female_betty",
    "en_male_cupid",
    "en_female_grandma",
    "en_male_m2_xhxs_m03_christmas",
    "en_male_santa_narration",
    "en_male_sing_deep_jingle",
    "en_male_santa_effect",
    "en_female_ht_f08_newyear",
    "en_male_wizard",
    "en_female_ht_f08_halloween",
    "en_female_ht_f08_glorious",
    "en_male_sing_funny_it_goes_up",
    "en_female_ht_f08_wonderful_world",
    "en_male_m2_xhxs_m03_silly",
    "en_female_emotional",
    "en_male_m03_sunshine_soon",
    "en_female_f08_warmy_breeze",
    "en_male_m03_lobby",
    "en_male_sing_funny_thanksgiving",
    "en_female_f08_salut_damour",
    "en_us_007",
    "en_us_009",
    "en_us_010",
    "en_au_002",
    "en_us_ghostface",
    "en_us_chewbacca",
    "en_us_c3po",
    "en_us_stitch",
    "en_us_stormtrooper",
    "en_us_rocket",
    "en_female_madam_leota",
    "en_male_ghosthost",
    "en_male_pirate"
  ],
  decentVoices: [
    "en_male_deadpool",
    "en_male_grinch",
    "en_male_ukbutler",
    "en_us_006",
    "en_us_ghostface",
  ]
};
